/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import UIDefeated from "./script/Game/UIDefeated"
import UILoding from "./script/Game/UILoding"
import UIOperation from "./script/Game/UIOperation"
import UIShare from "./script/Game/UIShare"
import UIShop_Goods from "./script/Game/UIShop_Goods"
import UIShop from "./script/Game/UIShop"
import UIStart from "./script/Game/UIStart"
import UIVictory from "./script/Game/UIVictory"
import GameUI from "./script/GameUI"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=720;
    static height:number=1280;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="Scene/UILoding.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/Game/UIDefeated.ts",UIDefeated);
        reg("script/Game/UILoding.ts",UILoding);
        reg("script/Game/UIOperation.ts",UIOperation);
        reg("script/Game/UIShare.ts",UIShare);
        reg("script/Game/UIShop_Goods.ts",UIShop_Goods);
        reg("script/Game/UIShop.ts",UIShop);
        reg("script/Game/UIStart.ts",UIStart);
        reg("script/Game/UIVictory.ts",UIVictory);
        reg("script/GameUI.ts",GameUI);
    }
}
GameConfig.init();